{% set data = load_setup_py_data() %}

package:
    name: his-geo-backend
    version: {{ data.get('version') }}

source:
    path: .

build:
    number: 0
    script: invoke install

requirements:
    develop:
        - python {{ python }}
        - autoflake ==1.3
        - black ==19.10b0
        - boto3 ==1.16.30
        - conda-build ==3.18.11
        - conda-verify ==3.1.1
        - flake8 ==3.8.4
        - flake8-comprehensions ==3.3.0
        - flake8-mutable ==1.2.0
        - invoke ==1.5.0
        - isort ==5.6.4
        - m2r2 ==0.2.7
        - mypy ==0.790
        - pytest ==6.2.1
        - pytest-asyncio ==0.14.0
        - pytest-cov ==2.10.1
        - pytest-mock ==3.4.0
        - setuptools ==49.6.0
        - sphinx ==3.0.4
        - sphinx_rtd_theme ==0.5.0
        - sphinxcontrib-plantuml ==0.17.1
        # Package specific:
    build:
        - python
        - invoke ==1.5.0
    run:
        - python
        - click >=7.1.2,7.*

about:
    license: PROPRIETARY
