#!/usr/bin/env bash

PATH="{invoke_path}:$PATH"
set -o errexit

(set -x; invoke check > /dev/null 2>&1)
if [ -d tests ]; then
  (set -x; invoke test > /dev/null 2>&1)
  (set -x; invoke test --behavioral > /dev/null 2>&1)
fi
if [ -d docs ]; then
  (set -x; invoke build-docs > /dev/null 2>&1)
fi
echo "Complete"
